[package]
name = "launcher"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[[bin]]
name = "GW2AddOnManager"
path = "src/main.rs"

[build-dependencies]
embed-resource = "2.5.0"

[dependencies]
jni = { version = "0.21.1", features = ["invocation"] }
serde = { version = "1.0.210", features = ["derive"] }
thiserror = "1.0.64"
thistermination = "1.1.0"
toml = "0.8.19"
winapi = { version = "0.3.9", features = ["wincon"] }