[versions]
compose = "1.6.11"
decompose = "3.1.0"
essenty = "2.1.0"
junit = "5.11.2"
kotlin = "2.0.0"
kotlinx-serialization = "1.7.1"
ktor = "2.3.12"
mockito = "5.12.0"


[libraries]
# com.arkivanov.decompose - Decompose
decompose = { module = "com.arkivanov.decompose:decompose", version.ref = "decompose" }
decompose-extensions-compose = { module = "com.arkivanov.decompose:extensions-compose", version.ref = "decompose" }

# com.arkivanov.essenty - Essenty
# https://github.com/arkivanov/Essenty
essenty-lifecycle-coroutines = { module = "com.arkivanov.essenty:lifecycle-coroutines", version.ref = "essenty" }

# io.ktor - Ktor
# https://github.com/ktorio/ktor
ktor-client-apache = { module = "io.ktor:ktor-client-apache", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-java = { module = "io.ktor:ktor-client-java", version.ref = "ktor" }
ktor-client-mock = { module = "io.ktor:ktor-client-mock", version.ref = "ktor" }

# org.jetbrains.kotlinx:kotlinx-serialization-[...] - kotlinx.serialization
# https://github.com/Kotlin/kotlinx.serialization
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

# org.junit - JUnit
# https://github.com/junit-team/junit5
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }

# org.mockito - Mockito
# https://github.com/mockito/mockito
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }


[plugins]
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose" }

# org.jetbrains.kotlin - Kotlin Gradle plugin
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-plugin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }