[versions]
caffeine = "3.2.0"
compose = "1.8.0-alpha03"
decompose = "3.3.0"
essenty = "2.5.0"
filekit-compose = "0.8.8"
jackson = "2.18.2"
junit = "5.12.0"
kotlin = "2.1.10"
kotlinx-coroutines = "1.10.1"
kotlinx-serialization = "1.8.0"
ktor = "3.1.1"
log4j = "2.24.3"
mockito = "5.15.2"
slf4j = "2.0.16"
turbine = "1.2.0"


[libraries]
# app.cash.turbine - Turbine
# https://github.com/cashapp/turbine
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }

# com.arkivanov.decompose - Decompose
decompose = { module = "com.arkivanov.decompose:decompose", version.ref = "decompose" }
decompose-extensions-compose = { module = "com.arkivanov.decompose:extensions-compose", version.ref = "decompose" }

# com.arkivanov.essenty - Essenty
# https://github.com/arkivanov/Essenty
essenty-lifecycle-coroutines = { module = "com.arkivanov.essenty:lifecycle-coroutines", version.ref = "essenty" }

# com.fasterxml.jackson.core - Jackson
# https://github.com/FasterXML/jackson
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }

# com.github.ben-manes.caffeine - Caffeine
# https://github.com/ben-manes/caffeine
caffeine = { module = "com.github.ben-manes.caffeine:caffeine", version.ref = "caffeine" }

# io.github.vinceglb:filekit-compose - FileKit
# https://github.com/vinceglb/FileKit
filekit-compose = { module = "io.github.vinceglb:filekit-compose", version.ref = "filekit-compose" }

# io.ktor - Ktor
# https://github.com/ktorio/ktor
ktor-client-apache = { module = "io.ktor:ktor-client-apache", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-java = { module = "io.ktor:ktor-client-java", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-client-mock = { module = "io.ktor:ktor-client-mock", version.ref = "ktor" }

# org.apache.logging.log4j - Log4j
# https://github.com/apache/logging-log4j2
log4j-core = { module = "org.apache.logging.log4j:log4j-core", version.ref = "log4j" }
log4j-slf4j2-impl = { module = "org.apache.logging.log4j:log4j-slf4j2-impl", version.ref = "log4j" }

# org.jetbrains.kotlinx:kotlinx-coroutines-[...] - kotlinx.coroutines
# https://github.com/Kotlin/kotlinx.coroutines
kotlinx-coroutines-slf4j = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-slf4j", version.ref = "kotlinx-coroutines" }

# org.jetbrains.kotlinx:kotlinx-serialization-[...] - kotlinx.serialization
# https://github.com/Kotlin/kotlinx.serialization
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

# org.junit - JUnit
# https://github.com/junit-team/junit5
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }

# org.mockito - Mockito
# https://github.com/mockito/mockito
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }

# org.slf4j - SLF4J
# https://github.com/qos-ch/slf4j
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }


[plugins]
# com.osmerion.gradle.jdk-tools - JDK Tools Gradle Plugin
# https://github.com/Osmerion/gradle-jdk-tools
gradle-jdkTools = { id = "com.osmerion.jdk-tools", version = "0.2.0" }

jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose" }

# org.jetbrains.kotlin - Kotlin Gradle plugin
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-plugin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }