name: CI
on:
  push:
    branches: [ "master" ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup MSVC Development Environment
        uses: TheMrMilchmann/setup-msvc-dev@79dac248aac9d0059f86eae9d8b5bfab4e95e97c # v4.0.0
        with:
          arch: x64

      - name: Setup Java
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: "temurin"
          java-version-file: .github/workflows/.java-version

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@f29f5a9d7b09a7c6b29859002d29d24e1674c884 # v5.0.1

      - name: Extract Version
        id: get_version
        shell: bash
        run: |
          BASE_VERSION=$(grep '^version=' gradle.properties | cut -d '=' -f 2)

          SEMVER_VERSION="${BASE_VERSION}-dev.${{ github.run_number }}"
          echo "version=$SEMVER_VERSION" >> $GITHUB_OUTPUT

          MS_VERSION="${BASE_VERSION}.${{ github.run_number }}"
          echo "msversion=$MS_VERSION" >> $GITHUB_OUTPUT

      - name: Build with Gradle
        env:
          MS_VERSION: ${{ steps.get_version.outputs.msversion }}
        run: ./gradlew build bundle --info -S --show-version -Pversion="${{ steps.get_version.outputs.version }}"

      - name: Build Installer
        env:
          VERSION: ${{ steps.get_version.outputs.version }}
          MS_VERSION: ${{ steps.get_version.outputs.msversion }}
        run: |
          pushd .
          cd installer
          msbuild -restore /p:Configuration=Release /p:Platform=x64 /p:MS_VERSION=$env:MS_VERSION /t:Rebuild
          mv "./bin/x64/Release/GW2AddOnManager.msi" "./bin/x64/Release/GW2AddOnManager-$env:VERSION.msi"
          popd

      - name: Upload Installer
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: installer
          path: "./installer/bin/x64/Release/GW2AddOnManager-${{ steps.get_version.outputs.version }}.msi"
          retention-days: 7

      - name: Upload Portable Bundle
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: portable
          path: "./build/bundles/GW2AddOnManager-${{ steps.get_version.outputs.version }}.zip"
          retention-days: 7
