name: CI
on:
  - pull_request
  - push
  - workflow_dispatch


jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSVC Development Environment
        uses: TheMrMilchmann/setup-msvc-dev@v3
        with:
          arch: x64

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version-file: .github/workflows/.java-version

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: ./gradlew build bundle --info -S --show-version

      - name: Build Installer
        run: |
          pushd .
          cd installer
          msbuild -restore /p:Configuration=Release /p:Platform=x64 /t:Rebuild
          popd

      - name: Upload Installer
        uses: actions/upload-artifact@v4
        with:
          name: installer
          path: "./installer/bin/x64/Release/GW2AddOnManager.msi"

      - name: Upload Portable Bundle
        uses: actions/upload-artifact@v4
        with:
          name: portable
          path: "./build/bundles/GW2AddOnManager-2.0.0.zip" # TODO Figure out how to handle the version