name: Publish
on:
  - workflow_dispatch
permissions:
  contents: write

concurrency:
  group: "publish"
  cancel-in-progress: false

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup MSVC Development Environment
        uses: TheMrMilchmann/setup-msvc-dev@79dac248aac9d0059f86eae9d8b5bfab4e95e97c # v4.0.0
        with:
          arch: x64

      - name: Setup Java
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: "temurin"
          java-version-file: .github/workflows/.java-version

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@0f4528296b4bc09e8ae0fc7be30185a4ab435545 # v6.0.0

      - name: Extract Version
        id: get_version
        shell: bash
        run: |
          BASE_VERSION=$(grep '^version=' gradle.properties | cut -d '=' -f 2)

          SEMVER_VERSION="${BASE_VERSION}"
          echo "version=$SEMVER_VERSION" >> $GITHUB_OUTPUT

          MS_VERSION="${BASE_VERSION}.65535"
          echo "msversion=$MS_VERSION" >> $GITHUB_OUTPUT

      - name: Build with Gradle
        run: ./gradlew build bundle --info -S --show-version -Pversion="${{ steps.get_version.outputs.version }}"

      - name: Build Installer
        env:
          VERSION: ${{ steps.get_version.outputs.version }}
          MS_VERSION: ${{ steps.get_version.outputs.msversion }}
        run: |
          pushd .
          cd installer
          msbuild -restore /p:Configuration=Release /p:Platform=x64 /p:MS_VERSION=$env:MS_VERSION /t:Rebuild
          mv "./bin/x64/Release/GW2AddOnManager.msi" "./bin/x64/Release/GW2AddonManager-$env:VERSION.msi"
          popd

      - name: Create VCS Tag
        id: vcs_tag
        env:
          VERSION: ${{ steps.get_version.outputs.version }}
        shell: bash
        run: |
          TAG_NAME="v${VERSION}"
          echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT
          echo "Processing tag: $TAG_NAME"

          if git rev-parse -q --verify "refs/tags/$TAG_NAME" >/dev/null; then
            echo "✅ Local tag '$TAG_NAME' already exists. Skipping 'git tag' creation."
          else
            echo "🏷️ Creating new local tag '$TAG_NAME'."
            git tag "$TAG_NAME"
            git push origin "$TAG_NAME"
          fi

      - name: Upload Installer
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: installer
          path: "./installer/bin/x64/Release/GW2AddonManager-${{ steps.get_version.outputs.version }}.msi"

      - name: Upload Portable Bundle
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: portable
          path: "./build/bundles/GW2AddonManager-${{ steps.get_version.outputs.version }}.zip"

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@153bb8e04406b158c6c84fc1615b65b24149a1fe # v2.6.1
        with:
          body_path: ${{ github.workspace }}/docs/changelog/${{ steps.get_version.outputs.version }}.md
          draft: true
          files: |
            ./installer/bin/x64/Release/GW2AddonManager-${{ steps.get_version.outputs.version }}.msi
            ./build/bundles/GW2AddonManager-${{ steps.get_version.outputs.version }}.zip
          overwrite_files: true
          preserve_order: true
          tag_name: ${{ steps.vcs_tag.outputs.tag_name }}

      - name: Extract GitHub Release Information
        id: extract_info
        shell: bash
        env:
          RELEASE_ASSETS_JSON: ${{ steps.create_release.outputs.assets }}
        run: |
          INSTALLER_URL=$(echo "$RELEASE_ASSETS_JSON" | jq -r '.[].browser_download_url | select(test("GW2AddonManager-.*\\.msi"))')
          PORTABLE_URL=$(echo "$RELEASE_ASSETS_JSON" | jq -r '.[].browser_download_url | select(test("GW2AddonManager-.*\\.zip"))')

          echo "installer_url=$INSTALLER_URL" >> $GITHUB_OUTPUT
          echo "portable_url=$PORTABLE_URL" >> $GITHUB_OUTPUT

      - name: Pull Manifest
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: gh-pages
          path: ./run/site

      - name: Update Manifest
        shell: bash
        env:
          VERSION: ${{ steps.get_version.outputs.version }}
          MS_VERSION: ${{ steps.get_version.outputs.msversion }}
          INSTALLER_URL: ${{ steps.extract_info.outputs.installer_url }}
          PORTABLE_URL: ${{ steps.extract_info.outputs.portable_url }}
        run: |
          ./gradlew updateManifest \
            --manifest-dir=./run/site/manifests \
            --installer-url=${INSTALLER_URL} \
            --portable-url=${PORTABLE_URL}

      - name: Push Manifest
        env:
          VERSION: ${{ steps.get_version.outputs.version }}
        shell: bash
        run: |
          cd ./run/site
          
          # Configure Git user for the commit
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          git add ./manifests
          git commit -m "Updated manifests for version ${VERSION}"
          git push

      - name: Publish Release
        run: gh release edit ${{ steps.vcs_tag.outputs.tag_name }} --draft=false
